### ISSUE TITLE
Error in startup

### ISSUE THREAD

**Issue by bserrao** [venturecommunism/meteor-taskwarrior#4]
Hi there, 

I'm trying to run the commit 4cdab380c63b801870885b69c398ebc339463c71 with task server integration, but i'm getting the following error:

Your app is crashing. Here's the latest log.

=> Errors prevented startup:

While building the application:
meteor-taskwarrior/packages/toastjs/toast-examples.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
meteor-taskwarrior/packages/moment/lib/moment/test/moment/create.js:435:40: Unexpected token ILLEGAL
meteor-taskwarrior/packages/moment/lib/moment/test/browser-prefix.js:6:3: Unexpected end of input
meteor-taskwarrior/packages/moment/lib/moment/test/browser-suffix.js:3:1: Unexpected token }

=> Your application has errors. Waiting for file change.
=> Meteor 1.0.1 is available. Update this project with 'meteor update'.

Could you help sorting this out?
Thanks a lot

**Comment by bserrao** [comment]
After a fresh reinstall, i have so more errors..

our app is crashing. Here's the latest log.

/home/bs/meteor-taskwarrior/.meteor/local/build/programs/server/boot.js:186
}).run();
   ^
TypeError: Object #<Object> has no method 'require'
    at app/server/taskwarrior.js:3:20
    at app/server/taskwarrior.js:212:3
    at /home/bs/meteor-taskwarrior/.meteor/local/build/programs/server/boot.js:155:10
    at Array.forEach (native)
    at Function._.each._.forEach (/root/.meteor/tools/6f23056589/lib/node_modules/underscore/underscore.js:79:11)
    at /home/bs/meteor-taskwarrior/.meteor/local/build/programs/server/boot.js:82:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

**Comment by venturecommunism** [comment]
One thing that's probably happening is that it's no longer called Meteor.require but rather Npm.require (or something like that).

I'm only going to be circling back to taskserver synchronization once I've had a chance to go through and replace most of the database updates with http://docs.meteor.com/#/full/observe and http://docs.meteor.com/#/full/observe_changes.

That'll mean a more explicit workflow for how task data changes and cleaner synchronization but it won't be for a long while.
